services:
  api:
    volumes:
      - type: bind
        source: ..
        target: /data/project/osmose/frontend
    command: bash

  web:
    volumes:
      - type: bind
        source: ../web
        target: /data/project/osmose/frontend/web
    entrypoint: /bin/sh
